language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

env:
    - TRAVIS_TESTING=true

services:
    - MySQL
    - PostgreSQL

before_install:
    - cpanm Dist::Zilla DBD::mysql DBD::Pg DBD::SQLite --quiet --notest

install:
    - dzil authordeps | xargs cpanm --quiet --notest
    - dzil listdeps | xargs cpanm --quiet --notest

before_script:    
    - psql -c 'CREATE DATABASE myapp_test;' -U postgres
    - mysql -e 'CREATE DATABASE myapp_test; USE myapp_test; CREATE TABLE session (id char(72), session_data varchar(2048), PRIMARY KEY (id)) CHARSET=utf8;'
    - psql -d 'myapp_test' -c 'CREATE TABLE session (id char(72), session_data varchar(2048), PRIMARY KEY (id));' -U postgres

script:
    - dzil smoke --release
