language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"

env:
    - TRAVIS_TESTING = true

services:
    - MySQL
    - PostgreSQL
    - SQLite3

before_install:
    - cpanm Dist::Zilla DBD::mysql DBD::Pg DBD::SQLite --quiet --notest

install:
    - dzil authordeps | xargs cpanm --quiet --notest
    - dzil listdeps | xargs cpanm --quiet --notest

before_script:
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database myapp_test;' -U postgres

script:
    - dzil smoke --author --release
